Traceback (most recent call last):
  File "orchestration.py", line 213, in <module>
    main()
  File "orchestration.py", line 203, in main
    logging=args.logging,
  File "/Users/sidharthmenon/workspace/classes/6.887/gyoza/models/model.py", line 46, in fit
    "args": args,
TypeError: 'Config' object is not callable